### PR TITLE
A few commits

### PR DESCRIPTION
**Pull request by nickl1**
I don't know if you want to develop Luapress completely by yourself, If that's the case tell me, I'll not take it as an offense, I just took the time to make this commit to learn a little bit of Lua and use the code for myself. I have a few more changes in mind. If you want me to start developing them and make more pull requests like this just tell me ;)

### CODE REVIEW

**Comment by Fizzadar** [comment]
Hi Nick,

Thanks for the request, I'm going to roll bits in manually, because:
- The io.open thing - all the file writing is done with io.open? So surly it does work on windows; it certainly should. os.rename feels awfully hacky considering we're checking if a file exists
- I'm going to make the html links an option in config

Otherwise I'll be adding all the additions in (over the next few hours).

**Comment by nickl1** [comment]
I'm using lua 5.1 in windows. If the build directory already exists and I try to run Luapress I get `Cant make the build directory`. I tried all the other functions from `io` and `lfs` and `os.rename` seems to be the simplest that will work both under windows and linux. Otherwise with `io.open` every time I want to generate the blog I have to delete the old build directory.

edit: I found a way to do it with `lfs.dir`. It should go after `lfs.mkdir` to work correctly.

Also, if you make the html links an option be sure to also change `index2.html`, `index3.html` to something like `/2/`, `/3/`.

I'd like to see a `/404/` page generated in the build directory so I can tell my web server to serve it in case it hits a 404 error. ;)

**Comment by Fizzadar** [comment]
Could you paste the output from running it here? - I’ve no way to test Windows :/. It should error out on ‘Cant make build/posts’ first if io.open isn’t working on directories. I’d much rather avoid os.rename because it’s not meant to be used in this way (and renaming the folders to themselves feels wrong!).

**Comment by nickl1** [comment]
Here you are. I run it two times. First time with the `build` directory empty and after, in the second run in throws me the error.

```
>lua -e "io.stdout:setvbuf 'no'" "luapress.lua" 
[Luapress]: Posts
    Post added: copy
    Post added: Hello World
    Post added: test
    Post added: test2
[Luapress]: Pages
    Page added: test
[Luapress]: Building posts
[Luapress]: Building pages
[Luapress]: Building indexes
[Luapress]: Building rss
[Luapress]: Copy inc
[Luapress]: Complete! Upload ./build to your website
>Exit code: 0
>lua -e "io.stdout:setvbuf 'no'" "luapress.lua" 
[Luapress]: Posts
    Post added: copy
    Post added: Hello World
    Post added: test
    Post added: test2
[Luapress]: Pages
    Page added: test
lua: luapress.lua:161: Cant make build/posts
stack traceback:
    [C]: in function 'error'
    luapress.lua:161: in main chunk
    [C]: ?
>Exit code: 1
```

Sure, `os.rename` feels wrong, but the above patch i posted with `lfs.dir` is a better solution. ;)

**edit:** when creating a page it should re-generate all the other pages because new pages won't appear on the menu of the old pages. also there's a problem with non english characters (for example Greek) on the post/page titles. they appear like `��` because windows uses `ISO-8859-7` for these characters when naming a file. a fix is to have something like `$name=Post Title` inside the file like `$date` ;)

**Comment by Fizzadar** [comment]
lfs.attributes also work as a replacement for the io.open (untested on Windows).

And for the page generation I'm planning a re-work of the build method for pages which will allow not regenerating all pages for it to work correctly (update most recent existing post when adding a new one).

And the title's can be changed $title=Post Title will work :)

**Comment by nickl1** [comment]
`lfs.attributes` also work under Windows.

for the titles: `$title=` won't work with greek characters. it will display it like text into the post. also if a file name has greek characters it's unable to correctly create the file inside the `posts` directory. i would recommend generating the files inside `posts` with names based on `$title=` if that exists. also having two `$var=` inside a post file will add `<p>﻿</p>` in the content and it will break the template. try installing greek on your keyboard to ensure it's working properly.

also for `index2.html`, `index3.html` you should make a delete function in case posts are removed.

i hope i'm not bothering you with all these comments. i really like Luapress and i'd like to see it developing into something bigger and greater.

edit: also `<title></title>` should contain post/page names instead of only just the site's name.

**Comment by nickl1** [comment]
also archive doesn't update and it doesn't check if `config.lua` exists.

**Comment by Fizzadar** [comment]
Hi Nick,

You're not bothering me at all - I'm very happy to see Luapress is being used :)
- The Greek characters I'm not sure I can do much about, the script searches for with the following pattern to get they key/value: `%$([%w]+)=([%w%p ]+)`, which covers all alphanumerics and punctuation characters for the value; Lua's pattern matching has no match for special characters, though I assumed they would be included in %w.
- Indexes will be re-worked when I re-order the generation stage (so a ./luapress.lua clean will empty the build/ directory, but otherwise it will only add what's needed)
- And my archive is working correctly? I left out a check for config.lua, the instructions are clear that it needs to be there now.

**Comment by nickl1** [comment]
After `=` you want to match any character with `.` till the line ends. I can't get it working correctly.

`%$([%w]+)=([^.]+)` matches the whole post. i can't get it to stop when it finds a new line.

**Comment by nickl1** [comment]
Just figured out how it should be:

`for k, v, c, d in s:gmatch( '%$([%w]+)=(.-)\n' ) do`

this will work with every kind of character you put there (english, greek, symbols, etc) and will stop matching to the end of the line. `.-` means it will stop in the first match it will find and `\n` means it will stop when the line changes.

[check lua patterns here](http://www.lua.org/manual/5.2/manual.html#6.4.1)

(oh and please reopen this ticket, i occidentally closed it)

**Comment by Fizzadar** [comment]
Just added this in the last commit!

**Pull request closed without merging**
